### ISSUE TITLE
Art Pieces > Art Pieces Details Screen

### ISSUE THREAD

**Issue by colebowl** [colebowl/artyyc-mobile#10]
When I click from the list into a piece the back button has no text and the screen has no heading. We should at change the text of the back button say "< List"

![image](https://user-images.githubusercontent.com/5973850/41440033-3d430d7e-6fea-11e8-98b6-9a6da25596e5.png)

**Comment by colebowl** [comment]
Note: Ignore my "1" and "2"

**Comment by srveale** [comment]
See PR #12
