### ISSUE TITLE
Art Pieces > List > Weird Padding

### ISSUE THREAD

**Issue by colebowl** [colebowl/artyyc-mobile#5]
There is some weird padding on the left of the list body of the art pieces screen

![image](https://user-images.githubusercontent.com/5973850/41438818-d602b140-6fe5-11e8-89ba-b7abd57ca2da.png)

**Comment by jtannas** [comment]
dibs

**Comment by colebowl** [comment]
I'm closing this issue as it's several years old and this project is no stagnant.
