### ISSUE TITLE
Art Pieces > Header

### ISSUE THREAD

**Issue by colebowl** [colebowl/artyyc-mobile#6]
We should do something with this header section. Either add the name of the screen or remove it or something. Let's have a discussion in this issue about what we should do.

![image](https://user-images.githubusercontent.com/5973850/41438866-02e08dc2-6fe6-11e8-8724-cc9b151e21ff.png)

**Comment by srveale** [comment]
The thing is that navigation stuff happens in the header, so I would vote not to scrap it altogether. But I like the screen title idea.

**Comment by colebowl** [comment]
I'm closing this issue as it's several years old and this project is no stagnant.
