### ISSUE TITLE
Art Pieces > Quadrant heading

### ISSUE THREAD

**Issue by colebowl** [colebowl/artyyc-mobile#7]
Should we remove this heading? I feel like the context of the buttons is pretty easy to figure out from the button labels. Thoughts?

![image](https://user-images.githubusercontent.com/5973850/41438935-2d03dece-6fe6-11e8-9df3-ac58f3ebad79.png)

**Comment by srveale** [comment]
I also feel like it's pretty intuitive without the label. Took it out
